import java.io.*;

public class Main {
  public static void main(String[] args) {
    try {
      // Open the file
      Reader reader = new FileReader("input.rs");

      // Start the Lexer (Flex_Rust is the class generated by JFlex)
      Flex_Rust lexer = new Flex_Rust(reader);

      // Loop through all tokens
      Token token;
      while ((token = lexer.yylex()) != null) {
        // Stop loop if EOF is reached
        if (token.type == TokenType.EOF) break;

        // Print token details
        System.out.println(token);
      }
        System.out.println("\n END \n");

    } catch (IOException e) {
      System.out.println("Error: Could not read 'input.rs'");
    }
  }
}